version: "3.5"

services:

  postgres:
    image: postgres:10
    restart: always
    env_file: .env
{% if cookiecutter.use_pgadmin == "y" %}
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    ports:
      - "8001:80"
    restart: always
    env_file: .env
{% endif %}
  django:
    depends_on: 
      - postgres
    build: .
    command: bash -c "coverage run --source='.' manage.py test myapp && coverage report"
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - .:/app
    stdin_open: true
    tty: true