version: "3.5"

services:

  postgres:
    image: postgres:10
    restart: always
    env_file: .env
  django:
    depends_on:
      - postgres
    build: .
    command: coverage
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - .:/app
    stdin_open: true
    tty: true
