version: "3.5"

services:

  postgres:
    image: postgres:13
    restart: always
    env_file: .env
  django:
    depends_on:
      - postgres
    build:
      context: .
      args:
        PIPENV_CFG: --dev
    command: migrate run_dev
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - .:/app
    stdin_open: true
    tty: true
